#----------------------------------------------------------------------------
#          _    _           Family:    aRVern System IPs
#         / \__/ \          Module:    read
#        /   /\   \         --------------------------------------------
#    ===/   /=========      Copyright: (c) 2026, aRVern-dev
#      /   / RV \   \       Contact:   arvernsilicon@gmail.com
#     /___/______\___\      GitHub:    https://github.com/Arvern-Silicon
#
# SPDX-License-Identifier: BSD-3-Clause
# Full license text is available in the LICENSE file at the repository root.
#----------------------------------------------------------------------------
# File Name          : read.tcl
# Module Description : Read, analyze, elaborate and link the RTL design.
#----------------------------------------------------------------------------

##############################################################################
#                                                                            #
#                               READ DESIGN RTL                              #
#                                                                            #
##############################################################################

set DESIGN_NAME      "ahb_aclint"

# RTL_SOURCE_FILES (+ RTL_INCDIRS) come from submit_syn.tcl, auto-generated
# by `flatten_filelist.py --format tcl` from rtl/verilog/filelist.f (the
# single source of truth shared with the simulation flow).
source ./submit_syn.tcl

set_svf ./results/$DESIGN_NAME.svf
define_design_lib WORK -path ./WORK
analyze -format verilog $RTL_SOURCE_FILES

# Parameter overrides, if a config was selected. rtl_params.tcl is generated by
# gen_rtl_params.py from sim/rtl_sim/bin/rtl_configs.py -- the same config set
# the simulation and both lint sweeps use, so a config cannot mean one thing
# here and another there. Absent the file, the RTL defaults are built.
set ELABORATE_PARAMS ""
if {[file exists ./rtl_params.tcl]} {
    source ./rtl_params.tcl
    if {[info exists RTL_CONFIG_LABEL]} {
        puts "RTL config: $RTL_CONFIG_LABEL"
    }
}

if {$ELABORATE_PARAMS ne ""} {
    puts "Elaborating with: $ELABORATE_PARAMS"
    eval "elaborate $DESIGN_NAME $ELABORATE_PARAMS"
    # A parameterized elaboration renames the design (e.g. ahb_aclint_1), which
    # would break every later `current_design $DESIGN_NAME`. Rename it back.
    set elaborated [get_object_name [current_design]]
    if {$elaborated ne $DESIGN_NAME} {
        puts "Renaming elaborated design $elaborated -> $DESIGN_NAME"
        rename_design $elaborated $DESIGN_NAME
        current_design $DESIGN_NAME
    }
} else {
    elaborate $DESIGN_NAME
}
link


# Check design structure after reading verilog
current_design $DESIGN_NAME
redirect ./results/report.check {check_design}
