#!/bin/bash

# Disable waveform dumping
SIMULATION_NODUMP=1
export SIMULATION_NODUMP

# Choose simulator:
#                   - iverilog  : Icarus Verilog  (default)
#                   - cver      : CVer
#                   - verilog   : Verilog-XL
#                   - ncverilog : NC-Verilog
#                   - vcs       : VCS
#                   - vsim      : Modelsim
#                   - isim      : Xilinx simulator
VERILOG_SIMULATOR=iverilog
export VERILOG_SIMULATOR


# Argument specifies number of regression loops
if [ $# -ne 1 ]; then
    LAST_REGRESSION=0
else
    LAST_REGRESSION=$(($1-1))
fi

# Cleanup from previous regression
LOG_DIR=./log
rm -rf $LOG_DIR/*

# Perform the regression runs
for (( ii=0; ii<=$LAST_REGRESSION; ii++ ))
  do

    # Cleanup & log directory setup
    LOG_DIR=./log/$ii
    mkdir -p $LOG_DIR
     
    # Custom CSR test patterns (asynchronous reset - default ASYNC_RST_EN=1)
    ../bin/runsim simple_rdwr                 | tee $LOG_DIR/simple_rdwr.log
    ../bin/runsim simple_rdonly               | tee $LOG_DIR/simple_rdonly.log
    ../bin/runsim supervisor_rdwr             | tee $LOG_DIR/supervisor_rdwr.log
    ../bin/runsim wen_zero                    | tee $LOG_DIR/wen_zero.log

    # Re-run the same test list with synchronous reset (ASYNC_RST_EN=0),
    # mirroring the arvern core's ASYNC_RST_EN config coverage.
    SIM_EXTRA_DEFINES="-D ASYNC_RST_EN=0"
    export SIM_EXTRA_DEFINES
    ../bin/runsim simple_rdwr                 | tee $LOG_DIR/simple_rdwr-sync.log
    ../bin/runsim simple_rdonly               | tee $LOG_DIR/simple_rdonly-sync.log
    ../bin/runsim supervisor_rdwr             | tee $LOG_DIR/supervisor_rdwr-sync.log
    ../bin/runsim wen_zero                    | tee $LOG_DIR/wen_zero-sync.log
    unset SIM_EXTRA_DEFINES


    # Report regression results
    ../bin/parse_results $LOG_DIR             | tee $LOG_DIR/../summary.$ii.log

done


if [ $LAST_REGRESSION != 0 ]; then
    ../bin/parse_summaries                    | tee $LOG_DIR/../regressions_summary.log
fi
