#!/bin/bash
#----------------------------------------------------------------------------
#          _    _           Family:    aRVern System IPs
#         / \__/ \          Module:    run_check_reset_style
#        /   /\   \         --------------------------------------------
#    ===/   /=========      Copyright: (c) 2026, aRVern-dev
#      /   / RV \   \       Contact:   arvernsilicon@gmail.com
#     /___/______\___\      GitHub:    https://github.com/Arvern-Silicon
#
# SPDX-License-Identifier: BSD-3-Clause
# Full license text is available in the LICENSE file at the repository root.
#----------------------------------------------------------------------------
# File Name          : run_check_reset_style
# Module Description : Run Synopsys PrimeTime to check the reset style of the
#                      synthesized ahb_sram_controller netlist (./results/<top>.gate.v).
#----------------------------------------------------------------------------

pt_shell -f check_reset_style_pt.tcl
