#----------------------------------------------------------------------------
#          _    _           Family:    aRVern System IPs
#         / \__/ \          Module:    read
#        /   /\   \         --------------------------------------------
#    ===/   /=========      Copyright: (c) 2026, aRVern-dev
#      /   / RV \   \       Contact:   arvernsilicon@gmail.com
#     /___/______\___\      GitHub:    https://github.com/Arvern-Silicon
#
# SPDX-License-Identifier: BSD-3-Clause
# Full license text is available in the LICENSE file at the repository root.
#----------------------------------------------------------------------------
# File Name          : read.tcl
# Module Description : Read, analyze, elaborate and link the RTL design.
#
#   The top and its parameters come from ./rtl_params.tcl, generated by
#   gen_rtl_params.py from sim/rtl_sim/bin/rtl_configs.py (the config table
#   shared with the simulation and lint sweeps). Each config names its own top:
#   arv_dtm_jtag, arv_dtm_uart, arv_dtm_i2c, arv_dtm_cjtag or the arv_dtm
#   wrapper. run_syn always writes the file (config 1 when none is selected).
#----------------------------------------------------------------------------

##############################################################################
#                                                                            #
#                               READ DESIGN RTL                              #
#                                                                            #
##############################################################################

# Config first: it names the top to elaborate.
set ELABORATE_PARAMS ""
if {[file exists ./rtl_params.tcl]} {
    source ./rtl_params.tcl
    if {[info exists RTL_CONFIG_LABEL]} {
        puts "RTL config: $RTL_CONFIG_LABEL"
    }
}
if {[info exists RTL_TOP]} {
    set DESIGN_NAME $RTL_TOP
} elseif {[info exists ::env(DESIGN_NAME)]} {
    set DESIGN_NAME $::env(DESIGN_NAME)
} else {
    puts "ERROR: no ./rtl_params.tcl and no DESIGN_NAME -- run synthesis through run_syn"
    exit 1
}

# RTL_SOURCE_FILES (+ RTL_INCDIRS) come from submit_syn.tcl, auto-generated
# by `flatten_filelist.py --format tcl` from rtl/verilog/filelist.f (the
# single source of truth shared with the simulation flow). Every transport top
# compiles from the same RTL set.
source ./submit_syn.tcl

set_svf ./results/$DESIGN_NAME.svf
define_design_lib WORK -path ./WORK
analyze -format verilog $RTL_SOURCE_FILES

if {$ELABORATE_PARAMS ne ""} {
    puts "Elaborating $DESIGN_NAME with: $ELABORATE_PARAMS"
    eval "elaborate $DESIGN_NAME $ELABORATE_PARAMS"
    # A parameterized elaboration renames the design; rename it back so every
    # later `current_design $DESIGN_NAME` still resolves.
    set elaborated [get_object_name [current_design]]
    if {$elaborated ne $DESIGN_NAME} {
        puts "Renaming elaborated design $elaborated -> $DESIGN_NAME"
        rename_design $elaborated $DESIGN_NAME
        current_design $DESIGN_NAME
    }
} else {
    elaborate $DESIGN_NAME
}
link


# Check design structure after reading verilog
current_design $DESIGN_NAME
redirect ./results/report.check {check_design}
