#!/bin/bash
#----------------------------------------------------------------------------
#          _    _           Family:    aRVern System IPs
#         / \__/ \          Module:    run_syn_jtag
#        /   /\   \         --------------------------------------------
#    ===/   /=========      Copyright: (c) 2026, aRVern-dev
#      /   / RV \   \       Contact:   arvernsilicon@gmail.com
#     /___/______\___\      GitHub:    https://github.com/Arvern-Silicon
#
# SPDX-License-Identifier: BSD-3-Clause
# Full license text is available in the LICENSE file at the repository root.
#----------------------------------------------------------------------------
# File Name          : run_syn_jtag
# Module Description : Wrapper around run_syn that pins the synthesis top to
#                      arv_dtm_jtag (its default config). Extra CLI args are
#                      forwarded.
#----------------------------------------------------------------------------

exec ./run_syn -design arv_dtm_jtag "$@"
