#----------------------------------------------------------------------------
#          _    _           Family:    aRVern System IPs
#         / \__/ \          Module:    vc_lint.tcl
#        /   /\   \         --------------------------------------------
#    ===/   /=========      Copyright: (c) 2026, aRVern-dev
#      /   / RV \   \       Contact:   arvernsilicon@gmail.com
#     /___/______\___\      GitHub:    https://github.com/Arvern-Silicon
#
# SPDX-License-Identifier: BSD-3-Clause
# Full license text is available in the LICENSE file at the repository root.
#----------------------------------------------------------------------------
# File Name          : vc_lint.tcl
# Module Description : VC Static (vcst) lint script for an aRVern IP -- read, elaborate, check, report.
#----------------------------------------------------------------------------
# Invoked by run_vclint from inside ./results/, so every relative path here is
# results-relative and all vcst scratch (WORK/, vcst_rtdb/, clog*, novas.*)
# stays inside the gitignored output dir.
#
# IDENTICAL IN EVERY IP, and structurally identical to
# arvern/lint/vc_static/vc_lint.tcl; the only difference is where the
# elaboration parameters come from (sim/rtl_sim/bin/rtl_configs.py here,
# run_config.json there).

set TOP        $::env(VCLINT_TOP)
set FILELIST   $::env(VCLINT_FILELIST)
set STAGES     $::env(VCLINT_STAGES)
set JOBS       $::env(VCLINT_JOBS)
set RULES      $::env(VCLINT_RULES)
set WAIVERS    $::env(VCLINT_WAIVERS)
set DO_LANG    $::env(VCLINT_DO_LANG)
set PARAMS_FILE $::env(VCLINT_PARAMS_FILE)

# rtl_params.tcl is generated by run_vclint from sim/rtl_sim/bin/rtl_configs.py
# -- the same table the simulation and Verilator-lint sweeps iterate -- and
# defines ELABORATE_PARAMS.
set ELAB_PARAMS ""
if {$PARAMS_FILE ne "" && [file exists $PARAMS_FILE]} {
    source $PARAMS_FILE
    if {[info exists ELABORATE_PARAMS]} { set ELAB_PARAMS $ELABORATE_PARAMS }
}

set search_path "."
set link_library " "
set enable_lang_checker true
set synth_preserve_sequential true
set_app_var analyze_skip_translate_body false
compress_hdl -enable

configure_hdl_tag -clear
configure_hdl_tag -enable -stage $STAGES

if {$RULES ne "" && [file exists $RULES]} {
    puts "\[vc_lint\] applying rule policy: $RULES"
    source $RULES
} else {
    puts "\[vc_lint\] RAW MODE -- no rule policy applied (all enabled stages active)"
}

define_design_lib WORK -path ./WORK
# The leading/trailing spaces matter: without them vcst parses the string as a
# command option and errors with "unknown option '-f ...'".
analyze -format verilog " -f $FILELIST "

if {$ELAB_PARAMS ne ""} {
    puts "\[vc_lint\] elaborating with parameters: $ELAB_PARAMS"
    eval "elaborate $TOP $ELAB_PARAMS"
    # vcst appends parameter values to the design name; rename back so the
    # reports and any waiver scoping refer to a stable design name.
    set elaborated [get_object_name [current_design]]
    if {$elaborated ne $TOP} {
        puts "\[vc_lint\] renaming design $elaborated -> $TOP"
        rename_design $elaborated $TOP
    }
} else {
    elaborate $TOP
}
current_design $TOP

if {$DO_LANG eq "1"} {
    check_hdl -lang -structure -j $JOBS
} else {
    check_hdl -structure
}

# Waivers MUST come after check_hdl: waive_hdl filters the violation database,
# so applying it earlier silently matches nothing.
if {$WAIVERS ne "" && [file exists $WAIVERS]} {
    puts "\[vc_lint\] applying waivers: $WAIVERS"
    source $WAIVERS
    puts "\[vc_lint\] waivers that matched nothing:"
    catch {waive_hdl -not_applied}
}

report_hdl -file ./report.lint_summary.txt
report_hdl -file ./report.lint_full.txt    -verbose -sort
# -only_waived and -include_waived are mutually exclusive; -only_waived alone
# is what produces the waived-items report.
report_hdl -file ./report.lint_waived.txt  -only_waived -verbose -gen_empty

foreach fam {CLK RST CONN CODING NAMING SIM SIMSYN SVSYN SYN XPROP} {
    report_hdl -file ./report.lint_by_family.txt -append -family $fam -list -gen_empty
}

quit
